foreground            #f3eefc
background            #120c1e

selection_foreground  #120c1e
selection_background  #b56cff

# Normal colors
color0   #1b1328
color1   #ff6b6b
color2   #71d17b
color3   #ffb86b
color4   #53c7ff
color5   #b56cff
color6   #7ce8ff
color7   #ece7f7

# Bright colors
color8   #45305d
color9   #ff8a80
color10  #9cf5a6
color11  #ffd27d
color12  #84ddff
color13  #d4a2ff
color14  #b3f3ff
color15  #ffffff

# URLs
url_color #ffb86b

# Cursor
cursor #ffb86b

# Tabs
active_tab_foreground   #ffffff
active_tab_background   #b56cff

inactive_tab_foreground #d6c9e8
inactive_tab_background #241734
