splash = false
ipc = true

wallpaper {
    monitor = DP-1
    path = /home/Spring/Pictures/ninja-gaiden-4.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/Spring/Pictures/ninja-gaiden-master-collection.jpg
    fit_mode = cover
}
